### ISSUE TITLE
setClearButtonCaption() to allow localisation

### ISSUE THREAD

**Issue by slibert** [maxschuster/Vaadin-SignatureField#3]
Hi again,

Could be great also to be able to localize or customize buttons captions.
Some setClearButtonCaption(String caption) could be a nice add :-)

Regards

**Comment by maxschuster** [comment]
The contents of the clear button can be customized by css.

Here's an example:

``` css
.signaturefield .signaturefield-clearbutton {
    border-radius: 5px;
    padding: 2px;
}
.signaturefield .signaturefield-clearbutton:before {
    content: "Hasta la vista, baby";
    width: auto;
}
```
